{% set name = "qpad" %}
{% set version = "1.6.3" %}

{% set build = 1 %}


package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://github.com/UCLA-Plasma-Simulation-Group/QPAD/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 99356ee017650f02ac36b2fb34d0e1da2989c7ef05992034484eeff6e8652fbe


build:
  number: {{ build }}
  skip: true  # [win]
  script: 
    - mkdir -p $PREFIX/bin
    - mkdir -p $PREFIX/lib
    - mkdir -p $PREFIX/include
    - mkdir -p bin
    - export PREFIX="${PREFIX}"
    - echo $CFLAGS
    - echo $FFLAGS
    - make PREFIX="${PREFIX}" \
        FC_OPTS="${FFLAGS} -fdefault-real-8 -fdefault-double-8 -fopenmp -ffree-form" \
        CC_OPTS="${CFLAGS} -O -std=c99" \
        LDF="-L${PREFIX}/lib -lHYPRE -ljsonfortran -lhdf5hl_fortran -lhdf5_fortran -lhdf5_hl -lhdf5 -lz"
    - cp ./bin/qpad.e $PREFIX/bin/
    - make clean
    - make PREFIX="${PREFIX}" IF_OPENPMD=1 \
        FC_OPTS="${FFLAGS} -fdefault-real-8 -fdefault-double-8 -fopenmp -ffree-form" \
        CC_OPTS="${CFLAGS} -O -std=c99" \
        LDF="-L${PREFIX}/lib -lHYPRE -ljsonfortran -lhdf5hl_fortran -lhdf5_fortran -lhdf5_hl -lhdf5 -lz"
    - cp ./bin/qpad.e $PREFIX/bin/qpad-pmd.e
    
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }} 
    - make
    - {{ mpi }}
    - llvm-openmp  # [osx]
    

  host:
    - hdf5 * mpi_{{ mpi }}* 
    - hypre >=2.32.0 mpi_{{ mpi }}*
    - {{ mpi }}
    - json-fortran
    - zlib
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - libgcc   # [osx]

  run:
    - llvm-openmp  # [osx]
    - libgcc   # [osx]
    

test:
  source_files:
    - input_file/blowout_regime/qpinput_tri-gaussian.json
  commands:
    - cp input_file/blowout_regime/qpinput_tri-gaussian.json qpinput.json 
    - qpad.e
    - qpad-pmd.e 

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  license_url: https://github.com/UCLA-Plasma-Simulation-Group/QPAD/blob/main/LICENSE
  summary: "QPAD (QuickPIC with Azimuthal Decompisition) is a quasi-static, quasi-3D (r-z) electromagnetic particle-in-cell code"
  home: https://github.com/UCLA-Plasma-Simulation-Group/QPAD

extra:
  recipe-maintainers:
    - tdalichaouch
    - tsung1029
